/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => VirtualProjectSpacePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// spaceManager.ts
var import_obsidian = require("obsidian");
var SpaceManager = class {
  constructor(app, settings, saveSettingsCallback) {
    this.app = app;
    this.settings = settings;
    this.saveSettingsCallback = saveSettingsCallback;
  }
  getSpaces() {
    return this.settings.spaces;
  }
  getSpace(id) {
    return this.settings.spaces.find((s) => s.id === id);
  }
  async createSpace(name, icon = "lucide-folder", color = "#4CAF50") {
    const newSpace = {
      id: crypto.randomUUID ? crypto.randomUUID() : Math.random().toString(36).substring(2, 15),
      name,
      icon,
      color,
      createdAt: (/* @__PURE__ */ new Date()).toISOString().split("T")[0],
      files: [],
      folders: [],
      tags: [],
      queries: []
    };
    this.settings.spaces.push(newSpace);
    await this.saveSettingsCallback();
    return newSpace;
  }
  async updateSpace(id, updates) {
    const space = this.getSpace(id);
    if (space) {
      Object.assign(space, updates);
      await this.saveSettingsCallback();
    }
  }
  async deleteSpace(id) {
    this.settings.spaces = this.settings.spaces.filter((s) => s.id !== id);
    if (this.settings.activeSpaceId === id) {
      this.settings.activeSpaceId = void 0;
    }
    await this.saveSettingsCallback();
  }
  async duplicateSpace(id) {
    const source = this.getSpace(id);
    if (!source)
      return void 0;
    const newSpace = {
      ...JSON.parse(JSON.stringify(source)),
      id: crypto.randomUUID ? crypto.randomUUID() : Math.random().toString(36).substring(2, 15),
      name: `${source.name} Copy`,
      createdAt: (/* @__PURE__ */ new Date()).toISOString().split("T")[0]
    };
    this.settings.spaces.push(newSpace);
    await this.saveSettingsCallback();
    return newSpace;
  }
  async addFileToSpace(spaceId, filePath) {
    const space = this.getSpace(spaceId);
    if (space && !space.files.includes(filePath)) {
      space.files.push(filePath);
      await this.saveSettingsCallback();
    }
  }
  async removeFileFromSpace(spaceId, filePath) {
    const space = this.getSpace(spaceId);
    if (space) {
      space.files = space.files.filter((f) => f !== filePath);
      await this.saveSettingsCallback();
    }
  }
  async addFolderToSpace(spaceId, folderPath) {
    const space = this.getSpace(spaceId);
    if (space && !space.folders.includes(folderPath)) {
      space.folders.push(folderPath);
      await this.saveSettingsCallback();
    }
  }
  async removeFolderFromSpace(spaceId, folderPath) {
    const space = this.getSpace(spaceId);
    if (space) {
      space.folders = space.folders.filter((f) => f !== folderPath);
      await this.saveSettingsCallback();
    }
  }
  async addTagToSpace(spaceId, tag) {
    const cleanTag = tag.replace("#", "");
    const space = this.getSpace(spaceId);
    if (space && !space.tags.includes(cleanTag)) {
      space.tags.push(cleanTag);
      await this.saveSettingsCallback();
    }
  }
  async removeTagFromSpace(spaceId, tag) {
    const cleanTag = tag.replace("#", "");
    const space = this.getSpace(spaceId);
    if (space) {
      space.tags = space.tags.filter((t) => t !== cleanTag);
      await this.saveSettingsCallback();
    }
  }
  async addQueryToSpace(spaceId, rule) {
    const space = this.getSpace(spaceId);
    if (space) {
      const exists = space.queries.some((q) => q.type === rule.type && q.value === rule.value);
      if (!exists) {
        space.queries.push(rule);
        await this.saveSettingsCallback();
      }
    }
  }
  async removeQueryFromSpace(spaceId, ruleIndex) {
    const space = this.getSpace(spaceId);
    if (space && space.queries[ruleIndex]) {
      space.queries.splice(ruleIndex, 1);
      await this.saveSettingsCallback();
    }
  }
  // Handle file renames across the entire Vault
  async handleFileRename(oldPath, newPath) {
    let changed = false;
    for (const space of this.settings.spaces) {
      const fileIdx = space.files.indexOf(oldPath);
      if (fileIdx !== -indexOffsetMinusOne(fileIdx) && fileIdx !== -1) {
        space.files[fileIdx] = newPath;
        changed = true;
      }
      const folderIdx = space.folders.indexOf(oldPath);
      if (folderIdx !== -1) {
        space.folders[folderIdx] = newPath;
        changed = true;
      } else {
        space.folders = space.folders.map((f) => {
          if (f === oldPath) {
            changed = true;
            return newPath;
          }
          if (f.startsWith(oldPath + "/")) {
            changed = true;
            return newPath + f.substring(oldPath.length);
          }
          return f;
        });
      }
      if (space.dashboard === oldPath) {
        space.dashboard = newPath;
        changed = true;
      }
    }
    if (changed) {
      await this.saveSettingsCallback();
    }
  }
  // Handle file deletions
  async handleFileDelete(filePath) {
    let changed = false;
    for (const space of this.settings.spaces) {
      const originalLen = space.files.length;
      space.files = space.files.filter((f) => f !== filePath);
      if (space.files.length !== originalLen)
        changed = true;
      const origFolderLen = space.folders.length;
      space.folders = space.folders.filter((f) => f !== filePath);
      if (space.folders.length !== origFolderLen)
        changed = true;
      if (space.dashboard === filePath) {
        space.dashboard = void 0;
        changed = true;
      }
    }
    if (changed) {
      await this.saveSettingsCallback();
    }
  }
  // Resolve all files belonging to a project space (both static and dynamic rules)
  getSpaceFiles(spaceId) {
    const space = this.getSpace(spaceId);
    if (!space)
      return [];
    const allFiles = this.app.vault.getFiles();
    const matchedFiles = /* @__PURE__ */ new Set();
    for (const path of space.files) {
      const file = this.app.vault.getAbstractFileByPath(path);
      if (file instanceof import_obsidian.TFile) {
        matchedFiles.add(file);
      }
    }
    for (const folderPath of space.folders) {
      const folder = this.app.vault.getAbstractFileByPath(folderPath);
      if (folder instanceof import_obsidian.TFolder || folderPath === "/" || folderPath === "") {
        for (const file of allFiles) {
          if (file.path.startsWith(folderPath === "/" ? "" : folderPath + "/")) {
            matchedFiles.add(file);
          }
        }
      }
    }
    if (space.tags.length > 0 || this.settings.enableDynamicQuery && space.queries.length > 0) {
      for (const file of allFiles) {
        const cache = this.app.metadataCache.getFileCache(file);
        if (space.tags.length > 0) {
          const fileTags = this.getFileTags(file);
          const hasMatchingTag = space.tags.some((t) => fileTags.includes(t.toLowerCase()));
          if (hasMatchingTag) {
            matchedFiles.add(file);
            continue;
          }
        }
        if (this.settings.enableDynamicQuery && space.queries.length > 0) {
          let matchesQuery = false;
          for (const query of space.queries) {
            if (query.type === "tag") {
              const cleanQueryTag = query.value.replace("#", "").toLowerCase();
              const fileTags = this.getFileTags(file);
              if (fileTags.includes(cleanQueryTag)) {
                matchesQuery = true;
                break;
              }
            } else if (query.type === "folder") {
              const cleanFolder = (0, import_obsidian.normalizePath)(query.value);
              if (file.path.startsWith(cleanFolder === "/" ? "" : cleanFolder + "/")) {
                matchesQuery = true;
                break;
              }
            } else if (query.type === "name") {
              const pattern = query.value.replace(/\*/g, ".*");
              const regex = new RegExp(`^${pattern}$`, "i");
              if (regex.test(file.name) || regex.test(file.basename)) {
                matchesQuery = true;
                break;
              }
            }
          }
          if (matchesQuery) {
            matchedFiles.add(file);
          }
        }
      }
    }
    return Array.from(matchedFiles);
  }
  // Utility to extract tags (lowercase, without '#') from file cache
  getFileTags(file) {
    const cache = this.app.metadataCache.getFileCache(file);
    if (!cache)
      return [];
    const tags = /* @__PURE__ */ new Set();
    if (cache.frontmatter) {
      const fmTags = cache.frontmatter.tags || cache.frontmatter.tag;
      if (Array.isArray(fmTags)) {
        fmTags.forEach((t) => tags.add(String(t).replace("#", "").toLowerCase().trim()));
      } else if (typeof fmTags === "string") {
        fmTags.split(",").forEach((t) => tags.add(t.replace("#", "").toLowerCase().trim()));
      }
    }
    if (cache.tags) {
      cache.tags.forEach((t) => tags.add(t.tag.replace("#", "").toLowerCase().trim()));
    }
    return Array.from(tags);
  }
};
function indexOffsetMinusOne(idx) {
  return 0;
}

// spaceExplorerView.ts
var import_obsidian3 = require("obsidian");

// spaceModal.ts
var import_obsidian2 = require("obsidian");
var SpaceModal = class extends import_obsidian2.Modal {
  constructor(app, onSubmit, space) {
    super(app);
    this.name = "";
    this.icon = "lucide-folder";
    this.color = "#4CAF50";
    this.onSubmit = onSubmit;
    this.space = space;
    if (this.space) {
      this.name = this.space.name;
      this.icon = this.space.icon;
      this.color = this.space.color;
    }
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: this.space ? "\u7F16\u8F91\u9879\u76EE\u7A7A\u95F4" : "\u65B0\u5EFA\u9879\u76EE\u7A7A\u95F4" });
    new import_obsidian2.Setting(contentEl).setName("\u7A7A\u95F4\u540D\u79F0").setDesc("\u4E3A\u60A8\u7684\u903B\u8F91\u9879\u76EE\u7A7A\u95F4\u547D\u540D").addText((text) => text.setValue(this.name).setPlaceholder("\u4F8B\u5982: Frontend Project").onChange((value) => {
      this.name = value;
    }));
    const icons = [
      { name: "\u9ED8\u8BA4\u6587\u4EF6\u5939", value: "lucide-folder" },
      { name: "\u4EE3\u7801", value: "lucide-code" },
      { name: "\u6587\u6863", value: "lucide-book" },
      { name: "\u7F51\u9875/\u5168\u7403", value: "lucide-globe" },
      { name: "\u6570\u636E\u5E93", value: "lucide-database" },
      { name: "\u4EFB\u52A1/\u5BF9\u52FE", value: "lucide-check-square" },
      { name: "\u706B\u7BAD", value: "lucide-rocket" },
      { name: "\u8BBE\u7F6E/\u9F7F\u8F6E", value: "lucide-settings" }
    ];
    new import_obsidian2.Setting(contentEl).setName("\u7A7A\u95F4\u56FE\u6807").setDesc("\u5728\u4FA7\u8FB9\u680F\u663E\u793A\u7684\u56FE\u6807").addDropdown((dropdown) => {
      icons.forEach((i) => dropdown.addOption(i.value, i.name));
      dropdown.setValue(this.icon);
      dropdown.onChange((value) => {
        this.icon = value;
      });
    });
    const colors = [
      { name: "\u7FE0\u7EFF", value: "#4CAF50" },
      { name: "\u5929\u84DD", value: "#2196F3" },
      { name: "\u6DF1\u7D2B", value: "#9C27B0" },
      { name: "\u6D3B\u529B\u6A59", value: "#FF9800" },
      { name: "\u9B45\u60D1\u7C89", value: "#E91E63" },
      { name: "\u9752\u8272", value: "#00BCD4" },
      { name: "\u660E\u9EC4", value: "#FFEB3B" },
      { name: "\u9AD8\u7EA7\u7070", value: "#607D8B" }
    ];
    new import_obsidian2.Setting(contentEl).setName("\u4E3B\u9898\u8272").setDesc("\u8BE5\u7A7A\u95F4\u7684\u4E3B\u8272\u8C03").addColorPicker((colorPicker) => {
      colorPicker.setValue(this.color);
      colorPicker.onChange((value) => {
        this.color = value;
      });
    });
    new import_obsidian2.Setting(contentEl).addButton((btn) => btn.setButtonText(this.space ? "\u4FDD\u5B58\u4FEE\u6539" : "\u7ACB\u5373\u521B\u5EFA").setCta().onClick(() => {
      if (!this.name.trim()) {
        this.name = this.space ? this.space.name : "\u672A\u547D\u540D\u7A7A\u95F4";
      }
      this.onSubmit(this.name, this.icon, this.color);
      this.close();
    })).addButton((btn) => btn.setButtonText("\u53D6\u6D88").onClick(() => {
      this.close();
    }));
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// spaceExplorerView.ts
var VIEW_TYPE_SPACE_EXPLORER = "virtual-project-space-explorer";
var SpaceExplorerView = class extends import_obsidian3.ItemView {
  constructor(leaf, spaceManager) {
    super(leaf);
    this.searchKeyword = "";
    this.expandedPaths = /* @__PURE__ */ new Set();
    this.spaceManager = spaceManager;
  }
  getViewType() {
    return VIEW_TYPE_SPACE_EXPLORER;
  }
  getDisplayText() {
    return "\u9879\u76EE\u7A7A\u95F4";
  }
  getIcon() {
    return "rocket";
  }
  async onOpen() {
    this.render();
  }
  async onClose() {
  }
  setKeyword(kw) {
    this.searchKeyword = kw;
    this.render();
  }
  render() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("vps-explorer-container");
    const header = container.createDiv({ cls: "vps-explorer-header" });
    header.createDiv({ cls: "vps-explorer-title", text: "\u{1F680} \u9879\u76EE\u7A7A\u95F4" });
    const addBtn = header.createDiv({ cls: "vps-space-action-btn" });
    (0, import_obsidian3.setIcon)(addBtn, "plus");
    addBtn.setAttribute("title", "\u65B0\u5EFA\u7A7A\u95F4");
    addBtn.addEventListener("click", () => {
      new SpaceModal(this.app, async (name, icon, color) => {
        const space = await this.spaceManager.createSpace(name, icon, color);
        this.app.workspace.trigger("vps-space-activated", space.id);
        this.render();
      }).open();
    });
    const searchWrapper = container.createDiv({ cls: "vps-search-wrapper" });
    const searchInput = searchWrapper.createEl("input", {
      cls: "vps-search-input",
      type: "text",
      value: this.searchKeyword,
      placeholder: "\u641C\u7D22\u7A7A\u95F4\u6216\u6587\u4EF6..."
    });
    searchInput.addEventListener("input", (e) => {
      this.searchKeyword = e.target.value;
      this.render();
    });
    const activeSpaceId = this.app.plugins?.plugins?.["virtual-project-space"]?.settings?.activeSpaceId;
    const spaces = this.spaceManager.getSpaces();
    const spacesListEl = container.createDiv({ cls: "vps-spaces-list" });
    spaces.forEach((space) => {
      if (this.searchKeyword && !space.name.toLowerCase().includes(this.searchKeyword.toLowerCase())) {
        return;
      }
      const isActive = space.id === activeSpaceId;
      const spaceItem = spacesListEl.createDiv({
        cls: `vps-space-item ${isActive ? "is-active" : ""}`
      });
      spaceItem.style.setProperty("--space-color", space.color);
      const iconEl = spaceItem.createDiv({ cls: "vps-space-icon" });
      (0, import_obsidian3.setIcon)(iconEl, space.icon.replace("lucide-", ""));
      const infoEl = spaceItem.createDiv({ cls: "vps-space-info" });
      infoEl.createDiv({ cls: "vps-space-name", text: space.name });
      const fileCount = this.spaceManager.getSpaceFiles(space.id).length;
      infoEl.createDiv({ cls: "vps-space-meta", text: `${fileCount} \u4E2A\u5173\u8054\u6587\u4EF6` });
      const actionsEl = spaceItem.createDiv({ cls: "vps-space-actions" });
      const copyBtn = actionsEl.createDiv({ cls: "vps-space-action-btn" });
      (0, import_obsidian3.setIcon)(copyBtn, "copy");
      copyBtn.setAttribute("title", "\u590D\u5236\u7A7A\u95F4");
      copyBtn.addEventListener("click", async (e) => {
        e.stopPropagation();
        await this.spaceManager.duplicateSpace(space.id);
        this.render();
      });
      const editBtn = actionsEl.createDiv({ cls: "vps-space-action-btn" });
      (0, import_obsidian3.setIcon)(editBtn, "pencil");
      editBtn.setAttribute("title", "\u7F16\u8F91\u7A7A\u95F4");
      editBtn.addEventListener("click", (e) => {
        e.stopPropagation();
        new SpaceModal(this.app, async (name, icon, color) => {
          await this.spaceManager.updateSpace(space.id, { name, icon, color });
          this.render();
          this.app.workspace.trigger("vps-space-updated", space.id);
        }, space).open();
      });
      const deleteBtn = actionsEl.createDiv({ cls: "vps-space-action-btn" });
      (0, import_obsidian3.setIcon)(deleteBtn, "trash-2");
      deleteBtn.setAttribute("title", "\u5220\u9664\u7A7A\u95F4");
      deleteBtn.addEventListener("click", async (e) => {
        e.stopPropagation();
        if (confirm(`\u786E\u5B9A\u8981\u5220\u9664\u7A7A\u95F4 "${space.name}" \u5417\uFF1F\u6B64\u64CD\u4F5C\u4E0D\u4F1A\u5220\u9664\u7269\u7406\u6587\u4EF6\u3002`)) {
          await this.spaceManager.deleteSpace(space.id);
          this.render();
          this.app.workspace.trigger("vps-space-deleted", space.id);
        }
      });
      spaceItem.addEventListener("click", () => {
        this.app.workspace.trigger("vps-space-activated", space.id);
      });
    });
    if (activeSpaceId) {
      const activeSpace = this.spaceManager.getSpace(activeSpaceId);
      if (activeSpace) {
        const treeContainer = container.createDiv({ cls: "vps-tree-container" });
        const treeHeader = treeContainer.createDiv({ cls: "vps-tree-header" });
        treeHeader.createDiv({
          cls: "vps-tree-title",
          text: `${activeSpace.name} \u7684\u865A\u62DF\u89C6\u56FE`
        });
        const addFileBtn = treeHeader.createDiv({ cls: "vps-space-action-btn" });
        (0, import_obsidian3.setIcon)(addFileBtn, "file-plus");
        addFileBtn.setAttribute("title", "\u6253\u5F00 Dashboard \u9996\u9875");
        addFileBtn.addEventListener("click", () => {
          this.app.workspace.trigger("vps-open-dashboard", activeSpace.id);
        });
        const files = this.spaceManager.getSpaceFiles(activeSpaceId);
        if (files.length === 0) {
          const d = treeContainer.createDiv({
            text: '\u8BE5\u7A7A\u95F4\u6682\u65E0\u5173\u8054\u6587\u4EF6\u3002\u53F3\u952E\u6587\u4EF6\u5217\u8868\u9009\u62E9 "Add to Space" \u52A0\u5165\u3002',
            cls: "vps-space-meta"
          });
          d.style.cssText = "padding: 8px;";
        } else {
          const rootNode = this.buildVirtualTree(files);
          this.renderTreeNodes(treeContainer, rootNode, 0, activeSpaceId);
        }
      }
    }
  }
  buildVirtualTree(files) {
    const root = {
      name: "root",
      path: "",
      isFolder: true,
      children: /* @__PURE__ */ new Map()
    };
    files.forEach((file) => {
      const parts = file.path.split("/");
      let current = root;
      for (let i = 0; i < parts.length; i++) {
        const part = parts[i];
        const isLast = i === parts.length - 1;
        const currentPath = parts.slice(0, i + 1).join("/");
        if (isLast) {
          current.children.set(part, {
            name: part,
            path: currentPath,
            isFolder: false,
            children: /* @__PURE__ */ new Map(),
            file
          });
        } else {
          if (!current.children.has(part)) {
            current.children.set(part, {
              name: part,
              path: currentPath,
              isFolder: true,
              children: /* @__PURE__ */ new Map()
            });
          }
          current = current.children.get(part);
        }
      }
    });
    return root;
  }
  renderTreeNodes(parentEl, node, depth, spaceId) {
    const sortedKeys = Array.from(node.children.keys()).sort((a, b) => {
      const nodeA = node.children.get(a);
      const nodeB = node.children.get(b);
      if (nodeA.isFolder && !nodeB.isFolder)
        return -1;
      if (!nodeA.isFolder && nodeB.isFolder)
        return 1;
      return a.localeCompare(b);
    });
    sortedKeys.forEach((key) => {
      const childNode = node.children.get(key);
      const isExpanded = this.expandedPaths.has(childNode.path);
      const nodeEl = parentEl.createDiv({
        cls: `vps-tree-node vps-tree-node-depth-${depth}`
      });
      const iconEl = nodeEl.createDiv({ cls: "vps-tree-node-icon" });
      (0, import_obsidian3.setIcon)(iconEl, childNode.isFolder ? isExpanded ? "chevron-down" : "chevron-right" : "file-text");
      nodeEl.createDiv({ cls: "vps-tree-node-name", text: childNode.name });
      nodeEl.addEventListener("contextmenu", (e) => {
        e.preventDefault();
        const menu = new import_obsidian3.Menu();
        if (childNode.isFolder) {
          menu.addItem((item) => {
            item.setTitle("\u79FB\u51FA\u6587\u4EF6\u5939\u4E0B\u7684\u6240\u6709\u6587\u4EF6").setIcon("folder-minus").onClick(async () => {
              const space = this.spaceManager.getSpace(spaceId);
              if (space) {
                space.files = space.files.filter((f) => !f.startsWith(childNode.path + "/"));
                space.folders = space.folders.filter((f) => f !== childNode.path && !f.startsWith(childNode.path + "/"));
                await this.spaceManager.updateSpace(spaceId, {
                  files: space.files,
                  folders: space.folders
                });
                this.render();
              }
            });
          });
        } else {
          menu.addItem((item) => {
            item.setTitle("\u4ECE\u7A7A\u95F4\u79FB\u51FA\u6587\u4EF6").setIcon("file-minus").onClick(async () => {
              await this.spaceManager.removeFileFromSpace(spaceId, childNode.path);
              this.render();
            });
          });
        }
        menu.showAtMouseEvent(e);
      });
      if (childNode.isFolder) {
        nodeEl.addEventListener("click", (e) => {
          e.stopPropagation();
          if (this.expandedPaths.has(childNode.path)) {
            this.expandedPaths.delete(childNode.path);
          } else {
            this.expandedPaths.add(childNode.path);
          }
          this.render();
        });
        if (isExpanded) {
          const childrenContainer = parentEl.createDiv();
          this.renderTreeNodes(childrenContainer, childNode, depth + 1, spaceId);
        }
      } else {
        nodeEl.addEventListener("click", (e) => {
          e.stopPropagation();
          if (childNode.file) {
            this.app.workspace.getLeaf(e.ctrlKey || e.metaKey).openFile(childNode.file);
          }
        });
      }
    });
  }
};

// spaceDashboardView.ts
var import_obsidian4 = require("obsidian");
var VIEW_TYPE_SPACE_DASHBOARD = "virtual-project-space-dashboard";
var SpaceDashboardView = class extends import_obsidian4.ItemView {
  constructor(leaf, spaceManager) {
    super(leaf);
    this.tasks = [];
    this.expandedPaths = /* @__PURE__ */ new Set();
    this.currentRenderVersion = 0;
    this.spaceManager = spaceManager;
  }
  getViewType() {
    return VIEW_TYPE_SPACE_DASHBOARD;
  }
  getDisplayText() {
    const activeSpaceId = this.app.plugins?.plugins?.["virtual-project-space"]?.settings?.activeSpaceId;
    const targetId = this.spaceId || activeSpaceId;
    if (targetId) {
      const space = this.spaceManager.getSpace(targetId);
      if (space)
        return `${space.name} - Dashboard`;
    }
    return "\u9879\u76EE\u63A7\u5236\u9762\u677F";
  }
  getIcon() {
    return "presentation";
  }
  setSpaceId(spaceId) {
    this.spaceId = spaceId;
    this.render();
  }
  async onOpen() {
    this.render();
  }
  async render() {
    const activeSpaceId = this.app.plugins?.plugins?.["virtual-project-space"]?.settings?.activeSpaceId;
    const targetId = activeSpaceId || this.spaceId;
    this.spaceId = targetId;
    const renderVersion = ++this.currentRenderVersion;
    const container = this.contentEl;
    if (!targetId) {
      container.empty();
      const d = container.createDiv({
        text: "\u8BF7\u5728\u4FA7\u8FB9\u680F\u9009\u62E9\u5E76\u6FC0\u6D3B\u4E00\u4E2A\u9879\u76EE\u7A7A\u95F4\u4EE5\u52A0\u8F7D Dashboard\u3002",
        cls: "vps-space-meta"
      });
      d.style.cssText = "padding: 24px; text-align: center;";
      return;
    }
    const space = this.spaceManager.getSpace(targetId);
    if (!space) {
      container.empty();
      const d = container.createDiv({
        text: "\u672A\u627E\u5230\u9009\u5B9A\u7684\u9879\u76EE\u7A7A\u95F4\u3002",
        cls: "vps-space-meta"
      });
      d.style.cssText = "padding: 24px; text-align: center;";
      return;
    }
    await this.scanTasks(space);
    if (renderVersion !== this.currentRenderVersion) {
      return;
    }
    container.empty();
    const dashboardEl = container.createDiv({ cls: "vps-dashboard-container" });
    const banner = dashboardEl.createDiv({ cls: "vps-dashboard-banner" });
    banner.style.setProperty("--banner-color-start", space.color);
    banner.style.setProperty("--banner-color-end", this.adjustColorBrightness(space.color, -30));
    banner.style.setProperty("--banner-color-shadow", this.hexToRgba(space.color, 0.4));
    const bannerIcon = banner.createDiv({ cls: "vps-dashboard-banner-icon" });
    (0, import_obsidian4.setIcon)(bannerIcon, space.icon.replace("lucide-", ""));
    const bannerInfo = banner.createDiv({ cls: "vps-dashboard-banner-info" });
    bannerInfo.createEl("h1", { cls: "vps-dashboard-banner-title", text: space.name });
    bannerInfo.createDiv({
      cls: "vps-dashboard-banner-meta",
      text: `\u521B\u5EFA\u4E8E ${space.createdAt} | \u5305\u542B ${space.files.length} \u4E2A\u76F4\u63A5\u5173\u8054\u6587\u4EF6\uFF0C${space.folders.length} \u4E2A\u6587\u4EF6\u5939`
    });
    const statsRow = dashboardEl.createDiv({ cls: "vps-stats-row" });
    const filesStat = statsRow.createDiv({ cls: "vps-stat-item" });
    filesStat.style.setProperty("--space-color", space.color);
    const filesCount = this.spaceManager.getSpaceFiles(space.id).length;
    filesStat.createDiv({ cls: "vps-stat-value", text: String(filesCount) });
    filesStat.createDiv({ cls: "vps-stat-label", text: "\u603B\u5173\u8054\u6587\u4EF6\u6570" });
    const pendingTasksCount = this.tasks.filter((t) => !t.completed).length;
    const tasksStat = statsRow.createDiv({ cls: "vps-stat-item" });
    tasksStat.style.setProperty("--space-color", space.color);
    tasksStat.createDiv({ cls: "vps-stat-value", text: String(pendingTasksCount) });
    tasksStat.createDiv({ cls: "vps-stat-label", text: "\u5F85\u529E\u4EFB\u52A1\u6570" });
    const rulesStat = statsRow.createDiv({ cls: "vps-stat-item" });
    rulesStat.style.setProperty("--space-color", space.color);
    const rulesCount = space.tags.length + space.queries.length;
    rulesStat.createDiv({ cls: "vps-stat-value", text: String(rulesCount) });
    rulesStat.createDiv({ cls: "vps-stat-label", text: "\u5173\u8054\u89C4\u5219\u6570" });
    const grid = dashboardEl.createDiv({ cls: "vps-dashboard-grid" });
    const filesCard = grid.createDiv({ cls: "vps-dashboard-card" });
    const filesTitle = filesCard.createDiv({ cls: "vps-dashboard-card-title", text: "\u{1F4C4} \u9879\u76EE\u6587\u4EF6" });
    const quickActions = filesTitle.createDiv({ cls: "vps-quick-actions" });
    const addNoteBtn = quickActions.createEl("button", { cls: "vps-btn vps-btn-secondary", text: "\u65B0\u5EFA\u7B14\u8BB0" });
    addNoteBtn.style.setProperty("--space-color", space.color);
    addNoteBtn.addEventListener("click", () => this.createNewSpaceNote(space));
    const filesList = filesCard.createDiv();
    filesList.style.cssText = "max-height: 300px; overflow-y: auto; display: flex; flex-direction: column; gap: 4px;";
    const allSpaceFiles = this.spaceManager.getSpaceFiles(space.id);
    if (allSpaceFiles.length === 0) {
      filesList.createDiv({ text: "\u5F53\u524D\u7A7A\u95F4\u65E0\u6587\u4EF6", cls: "vps-space-meta" });
    } else {
      const rootNode = this.buildVirtualTree(allSpaceFiles);
      this.renderTreeNodes(filesList, rootNode, 0);
    }
    const tasksCard = grid.createDiv({ cls: "vps-dashboard-card" });
    tasksCard.createDiv({ cls: "vps-dashboard-card-title", text: "\u2611\uFE0F \u5F85\u529E\u4E8B\u9879" });
    const tasksList = tasksCard.createDiv();
    tasksList.style.cssText = "max-height: 300px; overflow-y: auto; display: flex; flex-direction: column; gap: 8px;";
    if (this.tasks.length === 0) {
      tasksList.createDiv({ text: "\u672A\u5728\u5173\u8054\u6587\u4EF6\u4E2D\u627E\u5230\u5F85\u529E\u4EFB\u52A1", cls: "vps-space-meta" });
    } else {
      this.tasks.forEach((task, idx) => {
        const taskRow = tasksList.createDiv({
          cls: `vps-task-item ${task.completed ? "is-completed" : ""}`
        });
        const checkbox = taskRow.createEl("input", {
          cls: "vps-task-checkbox",
          type: "checkbox"
        });
        checkbox.checked = task.completed;
        checkbox.addEventListener("change", async () => {
          await this.toggleTaskCompletion(task);
          this.render();
        });
        const taskText = taskRow.createDiv({ cls: "vps-task-text", text: task.text });
        taskText.addEventListener("click", async () => {
          checkbox.checked = !checkbox.checked;
          await this.toggleTaskCompletion(task);
          this.render();
        });
        taskRow.createDiv({
          cls: "vps-task-source",
          text: task.file.basename
        });
      });
    }
  }
  async scanTasks(space) {
    const files = this.spaceManager.getSpaceFiles(space.id);
    this.tasks = [];
    for (const file of files) {
      if (file.extension !== "md")
        continue;
      const content = await this.app.vault.read(file);
      const lines = content.split("\n");
      lines.forEach((line, index) => {
        const match = line.match(/^\s*[-*]\s*\[([ xX])\]\s*(.*)$/);
        if (match) {
          const completed = match[1].toLowerCase() === "x";
          const text = match[2].trim();
          this.tasks.push({
            file,
            lineIndex: index,
            text,
            completed,
            rawLine: line
          });
        }
      });
    }
  }
  async toggleTaskCompletion(task) {
    const file = task.file;
    const content = await this.app.vault.read(file);
    const lines = content.split("\n");
    if (lines[task.lineIndex] !== void 0 && lines[task.lineIndex].includes(task.text)) {
      const line = lines[task.lineIndex];
      const newCompletedState = !task.completed;
      const updatedLine = line.replace(/(\s*[-*]\s*\[)([ xX])(\]\s*.*)/, `$1${newCompletedState ? "x" : " "}$3`);
      lines[task.lineIndex] = updatedLine;
      await this.app.vault.modify(file, lines.join("\n"));
      task.completed = newCompletedState;
      task.rawLine = updatedLine;
    }
  }
  async createNewSpaceNote(space) {
    let folderPath = "/";
    if (space.folders.length > 0) {
      folderPath = space.folders[0];
    }
    let noteName = "\u672A\u547D\u540D\u7B14\u8BB0";
    let fullPath = (0, import_obsidian4.normalizePath)(`${folderPath === "/" ? "" : folderPath + "/"}${noteName}.md`);
    let counter = 1;
    while (this.app.vault.getAbstractFileByPath(fullPath)) {
      noteName = `\u672A\u547D\u540D\u7B14\u8BB0 (${counter})`;
      fullPath = (0, import_obsidian4.normalizePath)(`${folderPath === "/" ? "" : folderPath + "/"}${noteName}.md`);
      counter++;
    }
    const templateContent = `# ${noteName}

\u521B\u5EFA\u4E8E\u9879\u76EE\u7A7A\u95F4: ${space.name}

## \u4EFB\u52A1
- [ ] \u5F00\u59CB\u7F16\u5199\u7B14\u8BB0...
`;
    const newFile = await this.app.vault.create(fullPath, templateContent);
    if (folderPath === "/") {
      await this.spaceManager.addFileToSpace(space.id, newFile.path);
    }
    this.app.workspace.getLeaf(false).openFile(newFile);
    this.render();
  }
  buildVirtualTree(files) {
    const root = {
      name: "root",
      path: "",
      isFolder: true,
      children: /* @__PURE__ */ new Map()
    };
    files.forEach((file) => {
      const parts = file.path.split("/");
      let current = root;
      for (let i = 0; i < parts.length; i++) {
        const part = parts[i];
        const isLast = i === parts.length - 1;
        const currentPath = parts.slice(0, i + 1).join("/");
        if (isLast) {
          current.children.set(part, {
            name: part,
            path: currentPath,
            isFolder: false,
            children: /* @__PURE__ */ new Map(),
            file
          });
        } else {
          if (!current.children.has(part)) {
            current.children.set(part, {
              name: part,
              path: currentPath,
              isFolder: true,
              children: /* @__PURE__ */ new Map()
            });
          }
          current = current.children.get(part);
        }
      }
    });
    return root;
  }
  renderTreeNodes(parentEl, node, depth) {
    const sortedKeys = Array.from(node.children.keys()).sort((a, b) => {
      const nodeA = node.children.get(a);
      const nodeB = node.children.get(b);
      if (nodeA.isFolder && !nodeB.isFolder)
        return -1;
      if (!nodeA.isFolder && nodeB.isFolder)
        return 1;
      return a.localeCompare(b);
    });
    sortedKeys.forEach((key) => {
      const childNode = node.children.get(key);
      const isExpanded = this.expandedPaths.has(childNode.path);
      const nodeEl = parentEl.createDiv({
        cls: `vps-tree-node vps-tree-node-depth-${depth}`
      });
      const iconEl = nodeEl.createDiv({ cls: "vps-tree-node-icon" });
      (0, import_obsidian4.setIcon)(iconEl, childNode.isFolder ? isExpanded ? "chevron-down" : "chevron-right" : "file-text");
      nodeEl.createDiv({ cls: "vps-tree-node-name", text: childNode.name });
      if (childNode.isFolder) {
        nodeEl.addEventListener("click", (e) => {
          e.stopPropagation();
          if (this.expandedPaths.has(childNode.path)) {
            this.expandedPaths.delete(childNode.path);
          } else {
            this.expandedPaths.add(childNode.path);
          }
          this.render();
        });
        if (isExpanded) {
          const childrenContainer = parentEl.createDiv();
          this.renderTreeNodes(childrenContainer, childNode, depth + 1);
        }
      } else {
        nodeEl.addEventListener("click", (e) => {
          e.stopPropagation();
          if (childNode.file) {
            this.app.workspace.getLeaf(false).openFile(childNode.file);
          }
        });
      }
    });
  }
  // Helper to adjust color brightness
  adjustColorBrightness(hex, percent) {
    let R = parseInt(hex.substring(1, 3), 16);
    let G = parseInt(hex.substring(3, 5), 16);
    let B = parseInt(hex.substring(5, 7), 16);
    R = Math.max(0, Math.min(255, R + R * percent / 100));
    G = Math.max(0, Math.min(255, G + G * percent / 100));
    B = Math.max(0, Math.min(255, B + B * percent / 100));
    const rHex = Math.round(R).toString(16).padStart(2, "0");
    const gHex = Math.round(G).toString(16).padStart(2, "0");
    const bHex = Math.round(B).toString(16).padStart(2, "0");
    return `#${rHex}${gHex}${bHex}`;
  }
  hexToRgba(hex, alpha) {
    const r = parseInt(hex.substring(1, 3), 16);
    const g = parseInt(hex.substring(3, 5), 16);
    const b = parseInt(hex.substring(5, 7), 16);
    return `rgba(${r}, ${g}, ${b}, ${alpha})`;
  }
};

// types.ts
var DEFAULT_SETTINGS = {
  enableDashboard: true,
  enableWorkspaceSync: true,
  enableDynamicQuery: true,
  showSpaceBadge: true,
  activeSpaceId: void 0,
  spaces: []
};

// main.ts
var VirtualProjectSpacePlugin = class extends import_obsidian5.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadPluginSettings();
    this.spaceManager = new SpaceManager(
      this.app,
      this.settings,
      async () => {
        await this.savePluginSettings();
        this.updateViews();
      }
    );
    this.registerView(
      VIEW_TYPE_SPACE_EXPLORER,
      (leaf) => new SpaceExplorerView(leaf, this.spaceManager)
    );
    this.registerView(
      VIEW_TYPE_SPACE_DASHBOARD,
      (leaf) => new SpaceDashboardView(leaf, this.spaceManager)
    );
    this.addRibbonIcon("rocket", "\u{1F680} \u9879\u76EE\u7A7A\u95F4 Explorer", () => {
      this.activateExplorerView();
    });
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (!(file instanceof import_obsidian5.TFile) && !(file instanceof import_obsidian5.TFolder))
          return;
        menu.addSeparator();
        menu.addItem((item) => {
          item.setTitle("\u6DFB\u52A0\u5230\u9879\u76EE\u7A7A\u95F4").setIcon("folder-plus").setSection("action");
          const subMenu = item.setSubmenu();
          this.settings.spaces.forEach((space) => {
            subMenu.addItem((subItem) => {
              subItem.setTitle(space.name).onClick(async () => {
                if (file instanceof import_obsidian5.TFile) {
                  await this.spaceManager.addFileToSpace(space.id, file.path);
                } else if (file instanceof import_obsidian5.TFolder) {
                  await this.spaceManager.addFolderToSpace(space.id, file.path);
                }
              });
            });
          });
          subMenu.addSeparator();
          subMenu.addItem((subItem) => {
            subItem.setTitle("+ \u65B0\u5EFA\u7A7A\u95F4\u5E76\u6DFB\u52A0").onClick(() => {
              new SpaceModal(this.app, async (name, icon, color) => {
                const newSpace = await this.spaceManager.createSpace(name, icon, color);
                if (file instanceof import_obsidian5.TFile) {
                  await this.spaceManager.addFileToSpace(newSpace.id, file.path);
                } else if (file instanceof import_obsidian5.TFolder) {
                  await this.spaceManager.addFolderToSpace(newSpace.id, file.path);
                }
                this.activateSpace(newSpace.id);
              }).open();
            });
          });
        });
      })
    );
    this.registerEvent(
      this.app.vault.on("rename", async (file, oldPath) => {
        await this.spaceManager.handleFileRename(oldPath, file.path);
        this.updateViews();
      })
    );
    this.registerEvent(
      this.app.vault.on("delete", async (file) => {
        await this.spaceManager.handleFileDelete(file.path);
        this.updateViews();
      })
    );
    const ws = this.app.workspace;
    this.registerEvent(
      ws.on("vps-space-activated", (spaceId) => {
        this.activateSpace(spaceId);
      })
    );
    this.registerEvent(
      ws.on("vps-open-dashboard", (spaceId) => {
        this.openDashboard(spaceId);
      })
    );
    this.registerEvent(
      ws.on("vps-space-updated", () => {
        this.updateViews();
      })
    );
    this.registerEvent(
      ws.on("vps-space-deleted", () => {
        this.updateViews();
      })
    );
    this.addCommand({
      id: "create-space",
      name: "\u65B0\u5EFA\u9879\u76EE\u7A7A\u95F4 (Create Space)",
      callback: () => {
        new SpaceModal(this.app, async (name, icon, color) => {
          const space = await this.spaceManager.createSpace(name, icon, color);
          this.activateSpace(space.id);
        }).open();
      }
    });
    this.addCommand({
      id: "switch-space",
      name: "\u5207\u6362\u9879\u76EE\u7A7A\u95F4 (Switch Space)",
      callback: () => {
        const spaces = this.spaceManager.getSpaces();
        if (spaces.length === 0) {
          alert("\u6682\u65E0\u9879\u76EE\u7A7A\u95F4\uFF0C\u8BF7\u5148\u521B\u5EFA\u4E00\u4E2A\uFF01");
          return;
        }
        const names = spaces.map((s, idx) => `${idx + 1}. ${s.name}`).join("\n");
        const selection = prompt(`\u8BF7\u8F93\u5165\u8981\u5207\u6362\u7684\u7A7A\u95F4\u5E8F\u53F7\uFF1A
${names}`);
        if (selection) {
          const idx = parseInt(selection) - 1;
          if (spaces[idx]) {
            this.activateSpace(spaces[idx].id);
          }
        }
      }
    });
    this.addCommand({
      id: "open-active-dashboard",
      name: "\u6253\u5F00\u5F53\u524D\u7A7A\u95F4\u63A7\u5236\u9762\u677F (Open Dashboard)",
      callback: () => {
        if (this.settings.activeSpaceId) {
          this.openDashboard(this.settings.activeSpaceId);
        } else {
          alert("\u672A\u6FC0\u6D3B\u4EFB\u4F55\u9879\u76EE\u7A7A\u95F4\uFF01");
        }
      }
    });
  }
  async onunload() {
    this.app.workspace.detachLeavesOfType(VIEW_TYPE_SPACE_EXPLORER);
    this.app.workspace.detachLeavesOfType(VIEW_TYPE_SPACE_DASHBOARD);
  }
  async loadPluginSettings() {
    const pluginDir = this.manifest.dir || ".obsidian/plugins/virtual-project-space";
    const dataPath = `${pluginDir}/spaces.json`;
    let loadedData = null;
    try {
      if (await this.app.vault.adapter.exists(dataPath)) {
        const content = await this.app.vault.adapter.read(dataPath);
        loadedData = JSON.parse(content);
      } else {
        loadedData = await this.loadData();
      }
    } catch (e) {
      console.warn("Failed to load spaces.json, falling back to empty settings", e);
    }
    this.settings = Object.assign({}, DEFAULT_SETTINGS, loadedData);
  }
  async savePluginSettings() {
    const pluginDir = this.manifest.dir || ".obsidian/plugins/virtual-project-space";
    const dataPath = `${pluginDir}/spaces.json`;
    try {
      if (!await this.app.vault.adapter.exists(pluginDir)) {
        await this.app.vault.adapter.mkdir(pluginDir);
      }
      await this.app.vault.adapter.write(dataPath, JSON.stringify(this.settings, null, 2));
    } catch (e) {
      console.error("Failed to write to spaces.json", e);
    }
    await this.saveData(this.settings);
  }
  async activateSpace(spaceId) {
    const oldSpaceId = this.settings.activeSpaceId;
    if (this.settings.enableWorkspaceSync && oldSpaceId) {
      const oldSpace = this.spaceManager.getSpace(oldSpaceId);
      if (oldSpace) {
        const openTabs = [];
        this.app.workspace.iterateAllLeaves((leaf) => {
          const file = leaf.view.file;
          if (file instanceof import_obsidian5.TFile) {
            openTabs.push(file.path);
          }
        });
        const activeFile = this.app.workspace.getActiveFile();
        await this.spaceManager.updateSpace(oldSpaceId, {
          workspace: {
            openTabs,
            activeTab: activeFile?.path
          }
        });
      }
    }
    this.settings.activeSpaceId = spaceId;
    await this.savePluginSettings();
    this.updateViews();
    if (this.settings.enableWorkspaceSync) {
      const newSpace = this.spaceManager.getSpace(spaceId);
      if (newSpace && newSpace.workspace && newSpace.workspace.openTabs.length > 0) {
        this.app.workspace.iterateRootLeaves((leaf) => {
          if (leaf.view.getViewType() === "markdown") {
            leaf.detach();
          }
        });
        for (const filePath of newSpace.workspace.openTabs) {
          const file = this.app.vault.getAbstractFileByPath(filePath);
          if (file instanceof import_obsidian5.TFile) {
            await this.app.workspace.getLeaf("tab").openFile(file);
          }
        }
      }
    }
    if (this.settings.enableDashboard) {
      this.openDashboard(spaceId);
    }
  }
  async activateExplorerView() {
    this.app.workspace.detachLeavesOfType(VIEW_TYPE_SPACE_EXPLORER);
    const leftLeaf = this.app.workspace.getLeftLeaf(false);
    if (leftLeaf) {
      await leftLeaf.setViewState({
        type: VIEW_TYPE_SPACE_EXPLORER,
        active: true
      });
    }
    const leaf = this.app.workspace.getLeavesOfType(VIEW_TYPE_SPACE_EXPLORER)[0];
    if (leaf) {
      this.app.workspace.revealLeaf(leaf);
    }
  }
  async openDashboard(spaceId) {
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_SPACE_DASHBOARD);
    let leaf;
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = this.app.workspace.getLeaf("tab");
      await leaf.setViewState({
        type: VIEW_TYPE_SPACE_DASHBOARD,
        active: true
      });
    }
    const view = leaf.view;
    view.setSpaceId(spaceId);
    this.app.workspace.revealLeaf(leaf);
  }
  updateViews() {
    this.app.workspace.getLeavesOfType(VIEW_TYPE_SPACE_EXPLORER).forEach((leaf) => {
      if (leaf.view instanceof SpaceExplorerView) {
        leaf.view.render();
      }
    });
    this.app.workspace.getLeavesOfType(VIEW_TYPE_SPACE_DASHBOARD).forEach((leaf) => {
      if (leaf.view instanceof SpaceDashboardView) {
        leaf.view.render();
      }
    });
  }
};
